# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddfcc515d592f7200dc4ffcce8c80c4e9b9df24da70dab9da8ae5b9357ccd239e49b3f1878091a0b6ce1ab65b5a5cce84b0a5c8e26c465e8a1d943b64ce3ad70

test:
  secret_key_base: ef851a44d9afd4893a8714ecbaf892ac82b90141146062712d746e5156488f3b455f4cd14b0e2f07762317757a012b06cb2e10a5a0ac90df633da8d70dfef319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
